name: "ci / staging"

on:
    push:
        branches:
            - staging
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: production
        permissions:
            contents: read
            packages: write
            deployments: write

        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Login to GHCR
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build and push container image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  platforms: linux/amd64
                  push: true
                  tags: ghcr.io/frc-emotion/staging-nautilus-backend:amd-latest
            - name: Connect to server and trigger redeploy of docker containers
              uses: appleboy/ssh-action@v1.0.0
              with:
                  host: "team2658.org"
                  username: "root"
                  key: ${{ secrets.staging }}
                  port: 22
                  script: |
                      docker logout ghcr.io
                      docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.staging }}
                      docker pull ghcr.io/frc-emotion/staging-nautilus-backend:amd-latest
                      docker stop nautilus-backend
                      docker rm nautilus-backend
                      docker run -d --name nautilus-backend -p 3000:3000 ghcr.io/frc-emotion/staging-nautilus-backend:amd-latest
                      docker logout ghcr.io