apiVersion: apps/v1
kind: Deployment
metadata:
  name: nautilus-backend
  namespace: production
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nautilus-backend
  template:
    metadata:
      labels:
        app: nautilus-backend
      annotations:
        configmap-hash: "${CONFIGMAP_HASH}"
        deploy-sha: "${GITHUB_SHA}"
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
      - name: nautilus-backend
        image: ghcr.io/frc-emotion/nautilus-backend:${GITHUB_SHA}
        ports:
        - containerPort: 7001
        envFrom:
        - configMapRef:
            name: nautilus-config
        readinessProbe:
          httpGet:
            path: /
            port: 7001
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: 7001
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: nautilus-backend
  namespace: production
spec:
  type: ClusterIP
  ports:
  - port: 7001
    targetPort: 7001
  selector:
    app: nautilus-backend
