name: "ci / prod"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      deployments: write

    env:
      DB_NAME: ${{ secrets.DB_NAME_PROD }}
      MONGO_URI: ${{ secrets.MONGO_URI_PROD }}
      ENVIRONMENT: ${{ secrets.ENVIRONMENT_PROD }}
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN_PROD }}
      JWT_SECRET: ${{ secrets.JWT_SECRET_PROD }}
      MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY_PROD }}
      MAILGUN_ENDPOINT: ${{ secrets.MAILGUN_ENDPOINT_PROD }}
      MAILGUN_FROM_EMAIL: ${{ secrets.MAILGUN_FROM_EMAIL_PROD }}
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      APP_MIGRATION_LEAD: ${{ secrets.APP_MIGRATION_LEAD_PROD }}
      APP_MIGRATION_MEETING: ${{ secrets.APP_MIGRATION_MEETING_PROD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.prod
          platforms: linux/amd64
          push: true
          tags: ghcr.io/frc-emotion/nautilus-backend:${{ github.sha }}

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save ${{ secrets.CLUSTER_NAME }}

      - name: Deploy to DigitalOcean Kubernetes
        run: |
          # Create namespace if it doesn't exist
          kubectl create namespace production --dry-run=client -o yaml | kubectl apply -f -
          
          # Create or update GHCR secret for pulling images
          kubectl create secret docker-registry ghcr-secret \
            --docker-server=ghcr.io \
            --docker-username=${{ github.actor }} \
            --docker-password=${{ secrets.GITHUB_TOKEN }} \
            --docker-email=${{ github.actor }}@users.noreply.github.com \
            --namespace=production \
            --dry-run=client -o yaml | kubectl apply -f -
          
          # Calculate ConfigMap hash to force pod restart when config changes
          CONFIGMAP_HASH=$(echo -n "${{ env.MONGO_URI }}${{ env.JWT_SECRET }}${{ env.DB_NAME }}${{ env.EXPO_TOKEN }}" | sha256sum | cut -d' ' -f1)
          echo "ConfigMap hash: $CONFIGMAP_HASH"
          
          # Create configmap using YAML definition
          cat <<EOF | kubectl apply -f -
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: nautilus-config
            namespace: production
          data:
            ENVIRONMENT: "${{ env.ENVIRONMENT }}"
            DB_NAME: "${{ env.DB_NAME }}"
            MONGO_URI: "${{ env.MONGO_URI }}"
            EXPO_TOKEN: "${{ env.EXPO_TOKEN }}"
            JWT_SECRET: "${{ env.JWT_SECRET }}"
            MAILGUN_API_KEY: "${{ env.MAILGUN_API_KEY }}"
            MAILGUN_ENDPOINT: "${{ env.MAILGUN_ENDPOINT }}"
            MAILGUN_FROM_EMAIL: "${{ env.MAILGUN_FROM_EMAIL }}"
            DISCORD_WEBHOOK: "${{ env.DISCORD_WEBHOOK }}"
            APP_MIGRATION_LEAD: "${{ env.APP_MIGRATION_LEAD }}"
            APP_MIGRATION_MEETING: "${{ env.APP_MIGRATION_MEETING }}"
          EOF

          # Export variables for envsubst (only the ones we want to replace)
          export GITHUB_SHA=${{ github.sha }}
          export CONFIGMAP_HASH=$CONFIGMAP_HASH
          
          # Apply Kubernetes manifests with proper variable substitution
          # Use envsubst with explicit variable list to avoid replacing unintended variables
          envsubst '${GITHUB_SHA} ${CONFIGMAP_HASH}' < k8s/production-manifests.yml | kubectl apply -f -
          
          # Give Kubernetes a moment to process the deployment update
          sleep 3
          
          # Force delete any pods that are stuck in Terminating state
          TERMINATING_PODS=$(kubectl get pods -n production -l app=nautilus-backend --field-selector=status.phase=Terminating -o jsonpath='{.items[*].metadata.name}' 2>/dev/null || echo "")
          if [ ! -z "$TERMINATING_PODS" ]; then
            echo "Force deleting terminating pods: $TERMINATING_PODS"
            kubectl delete pods -n production -l app=nautilus-backend --grace-period=0 --force 2>/dev/null || true
            sleep 2
          fi
          
          # Wait for rollout to complete with extended timeout
          echo "Waiting for deployment rollout..."
          kubectl rollout status deployment/nautilus-backend -n production --timeout=10m
